<a href="https://colab.research.google.com/github/setitfree/Everything/blob/main/Every_lec2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
my_array = np.array([1,2,3,4])    ## This is how we create an array
my_array

array([1, 2, 3, 4])

In [4]:
print(np.mean(my_array))    ## Dont iterate the numpy arras ever
## OR                       ## instead use the functions like "mean"
print(my_array.mean())

2.5
2.5


In [5]:
np.ones(10)   ## Generates 10 floating(default) dtype "1" 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10, int)  ## GENERATES 10 ints dtype"1"

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
first = np.ones(5)
second = np.ones(5)

In [8]:
first + second

array([2., 2., 2., 2., 2.])

In [9]:
first + 1

array([2., 2., 2., 2., 2.])

In [10]:
first * 5

array([5., 5., 5., 5., 5.])

In [11]:
first * second

array([1., 1., 1., 1., 1.])