<a href="https://colab.research.google.com/github/setitfree/Everything/blob/main/Every_lec2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lecture 2 Numpy

In [43]:
import numpy as np
my_array = np.array([1,2,3,4])    ## This is how we create an array
my_array

array([1, 2, 3, 4])

In [ ]:
print(np.mean(my_array))    ## Dont iterate the numpy arras ever
## OR                       ## instead use the functions like "mean"
print(my_array.mean())

2.5
2.5


In [ ]:
np.ones(10)   ## Generates 10 floating(default) dtype "1" 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10, int)  ## GENERATES 10 ints dtype"1"

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
first = np.ones(5)
second = np.ones(5)

In [ ]:
first + second

array([2., 2., 2., 2., 2.])

In [ ]:
first + 1

array([2., 2., 2., 2., 2.])

In [ ]:
first * 5

array([5., 5., 5., 5., 5.])

In [ ]:
first * second

array([1., 1., 1., 1., 1.])

In [6]:
one2d = np.ones([3,4])    ## Matrices of 1
one2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
one2d.shape

(3, 4)

In [17]:
print(one2d.sum())    ## Addition of above matrices
print(np.sum(one2d))

12.0
12.0


In [13]:
my_array2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])   ## Creating a matrices
my_array2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
my_array2d[2,3]   ## To get a particular number from matrices 

12

In [18]:
np.sum(one2d, axis = 0)

array([3., 3., 3., 3.])

In [19]:
np.sum(my_array2d, axis = 0)

array([15, 18, 21, 24])

In [27]:
np.sum(my_array2d, axis = 1)

array([10, 26, 42])

In [36]:
empty_array = np.empty((2,3))   ## This will create a empty array of 2 rows and 3 columns 
empty_array                     ## It doest not look empty but it is 

array([[0.94822937, 0.40663892, 0.47364769],
       [0.91328944, 0.13967061, 0.76280201]])

Now we have to fill some data in this matrix .
Below is how we fill it

In [37]:
for i in range(empty_array.shape[0]):    ## "0" tells which row to start. It always fills row wise.
  empty_array[i] = np.random.rand(3)      ## "3" is written because there are 3 coulums and we have to fill all column of 1st row
empty_array

array([[0.61478096, 0.74107724, 0.46559706],
       [0.53076634, 0.44821604, 0.04167947]])

In [ ]:
!wget https://raw.githubusercontent.com/setitfree/NumericalPython/main/data/combined_population_votes.csv

In [39]:
import pandas as pd
combined = pd.read_csv("combined_population_votes.csv")

In [40]:
combined.Votes.values   ## To get in series format

array([ 3,  9,  6, 11, 55,  9,  7,  3,  3, 29, 16,  4,  6,  4, 20, 11,  6,
        8,  8, 11, 10,  4, 16, 10, 10,  6,  3, 15,  3,  5,  4, 14,  5,  6,
       29, 18,  7,  7, 20,  4,  9,  3, 11, 38,  6, 13,  3, 12, 10,  5,  3])

In [44]:
combined.Votes.values

array([ 3,  9,  6, 11, 55,  9,  7,  3,  3, 29, 16,  4,  6,  4, 20, 11,  6,
        8,  8, 11, 10,  4, 16, 10, 10,  6,  3, 15,  3,  5,  4, 14,  5,  6,
       29, 18,  7,  7, 20,  4,  9,  3, 11, 38,  6, 13,  3, 12, 10,  5,  3])

In [42]:
combined[['popmills', 'Votes']].values    ## To get in dataframe format

array([[ 0.71 ,  3.   ],
       [ 4.78 ,  9.   ],
       [ 2.916,  6.   ],
       [ 6.392, 11.   ],
       [37.254, 55.   ],
       [ 5.029,  9.   ],
       [ 3.574,  7.   ],
       [ 0.602,  3.   ],
       [ 0.898,  3.   ],
       [18.801, 29.   ],
       [ 9.688, 16.   ],
       [ 1.36 ,  4.   ],
       [ 3.046,  6.   ],
       [ 1.568,  4.   ],
       [12.831, 20.   ],
       [ 6.484, 11.   ],
       [ 2.853,  6.   ],
       [ 4.339,  8.   ],
       [ 4.533,  8.   ],
       [ 6.548, 11.   ],
       [ 5.774, 10.   ],
       [ 1.328,  4.   ],
       [ 9.884, 16.   ],
       [ 5.304, 10.   ],
       [ 5.989, 10.   ],
       [ 2.967,  6.   ],
       [ 0.989,  3.   ],
       [ 9.535, 15.   ],
       [ 0.673,  3.   ],
       [ 1.826,  5.   ],
       [ 1.316,  4.   ],
       [ 8.792, 14.   ],
       [ 2.059,  5.   ],
       [ 2.701,  6.   ],
       [19.378, 29.   ],
       [11.537, 18.   ],
       [ 3.751,  7.   ],
       [ 3.831,  7.   ],
       [12.702, 20.   ],
       [ 1.053,  4.   ],
